Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets
# dir(datasets)
iris = datasets.load_iris()
#print(iris)
# print(iris.feature_names)
# print(iris.data)
#print(iris.target)
#print(iris.target_names)
#print(iris.DESCR)
#X, y = datasets.load_iris(return_X_y=True, as_frame=True)
#print(datasets.load_iris()["DESCR"])
#Extract feature matrix as NumPy array
X = iris.data
feature_names = iris.feature_names
# print(feature_names)
# print(type(X))
# print(X.shape)
means = np.mean(X, axis=0)
medians = np.median(X, axis=0)
stds = np.std(X, axis=0)
vars = np.var(X, axis=0)
highest_variance = np.max(vars)
print(f"{'Features Names'}\t\t | {'Mean'}\t\t | {'Median'}\t\t | {'Standard deviation'}\t\t | {'Variance'}\t\t")
for i in range(4):
    print(f"{feature_names[i].capitalize()}\t | {means[i]:.2f}\t\t | {medians[i]:.2f}\t\t\t | {stds[i]:.2f}\t\t\t\t | {vars[i]:.2f}\t\t")
    
print(f"Highest Variability: {highest_variance:.2f} - This indicates there is a huge variety and range of values")

Features Names		 | Mean		 | Median		 | Standard deviation		 | Variance
Sepal length (cm)	 | 5.84		 | 5.80			 | 0.83				 | 0.68
Sepal width (cm)	 | 3.06		 | 3.00			 | 0.43				 | 0.19
Petal length (cm)	 | 3.76		 | 4.35			 | 1.76				 | 3.10
Petal width (cm)	 | 1.20		 | 1.30			 | 0.76				 | 0.58
Highest Variability: 3.10 - This indicates there is a huge variety and range of values

In [2]:
petal_length = X[:,2]
#petal_length.shape
# Convert to (n,1)
petal_shape_convert = petal_length.reshape(-1,1)
petal_shape_convert.shape

(150, 1)

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [3]:
from sklearn.datasets import load_iris
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
#df.head()
samples = df.iloc[:100,-2:]
samples.shape
mean_val = df["petal length (cm)"].mean()
mask = df["petal length (cm)"] > mean_val
filtered_df = df[mask]
print(len(filtered_df))

93

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [4]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
means = np.mean(X, axis = 0)
stds = np.std(X, axis = 0)
# Applying formula
X_scaled = (X - means) /stds
#print(X_scaled)
scaled_mean = np.mean(X_scaled, axis = 0)
scaled_std = np.mean(X_scaled, axis = 0)
print(f"Mean: {np.round(means, 10)}")
print(f"Scaled Mean:{scaled_mean})")
print(f"Scaled Standard Deviation:{scaled_std} )")

Mean: [5.84333333 3.05733333 3.758      1.19933333]
Scaled Mean:[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15])
Scaled Standard Deviation:[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15] )

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [7]:
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [10]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [11]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Identifying feature types is important before modeling if data cleaning, assumption and model selection.

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [26]:
import seaborn as sns
df = sns.load_dataset("titanic")
female_first_class = df[(df['sex'] == 'female') &  (df['class'] == 'First') ]
female_first_class_survival_rate = female_first_class['survived'].mean()
overall_survival_rate = df['survived'].mean()
print("Female first class surival rate: ",female_first_class_survival_rate)
print("Overall Survival rate: ", overall_survival_rate)

Female first class surival rate:  0.9680851063829787
Overall Survival rate:  0.3838383838383838

Survival rate among women was higher as compared to man.

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [66]:
import numpy as np
import seaborn as sns
df_raw = sns.load_dataset("titanic")
df = df_raw.copy()
#df.head()
age_median = df['age'].median()
embarked_mode = df['age'].mode()
df['age'] = df['age'].fillna(df['age'].median())
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [67]:
df.drop(columns=['deck'], inplace=True)
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [65]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create: family_size = sibsp + parch + 1
2. Create:is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:Why engineered features improve ML models

In [83]:
import numpy as np
import seaborn as sns
df = sns.load_dataset("titanic")
df['family_size'] = df['sibsp'] + df['parch'] + 1
#df.head()
df['is_alone'] = (df['family_size'] == 1).astype(int)
#df.head()
survived_lonely = df.groupby('is_alone')['survived'].mean()
print(f"Survived Lonely: {survived_lonely[0]:.2f}")
print(f"Survived with family: {survived_lonely[1]:.2f}")

Survived Lonely: 0.51
Survived with family: 0.30

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [113]:
import seaborn as sns
df = sns.load_dataset("tips")
avg_tip_day = df.groupby('day', observed=True)['tip'].mean()
total_tip_sex = df.groupby('sex', observed=True)['tip'].sum()
#df.head()
df['tip_percentage'] = (df['tip'] /df['total_bill']).round(4) * 100
best_day = df.groupby('day', observed=True)['tip_percentage'].mean().idxmax()
highest_tip = df.groupby('day', observed=True)['tip_percentage'].mean().max()

In [108]:
df.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68

In [114]:
print("Best Day:",best_day)
print(f"Highest Tip: {highest_tip:.2f}")

Best Day: Fri
Highest Tip: 16.99

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [136]:
import seaborn as sns
import pandas as pd
df_raw = sns.load_dataset("tips")
tips = df_raw.copy()
tips['tip_percentage'] = ((tips['tip'] / tips['total_bill']) * 100).round(2)
under_tip_mask = (tips['total_bill'] > 20) & (tips['tip'] < 3)
#tips.info()
relevant_col = ['total_bill', 'tip', 'tip_percentage','day', 'time', 'sex']
under_tipper = tips.loc[under_tip_mask, relevant_col]
under_tipper.head()

    total_bill   tip  tip_percentage  day    time     sex
21       20.29  2.75           13.55  Sat  Dinner  Female
33       20.69  2.45           11.84  Sat  Dinner  Female
48       28.55  2.05            7.18  Sun  Dinner    Male
57       26.41  1.50            5.68  Sat  Dinner  Female
68       20.23  2.01            9.94  Sat  Dinner    Male

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [154]:
import numpy as np
array_a = np.array([[1,2],
         [3,4],
         [5,6]])
array_b = np.array([[7,8],
                   [9,10],
                   [11,12]])
vertical_stack = np.vstack((array_a, array_b))
hor_stack = np.hstack((array_a, array_b))
re_vertical_stack = vertical_stack.reshape(2, 6)
re_hor_stack = hor_stack.reshape(2, 6)
print(re_hor_stack )

[[ 1  2  7  8  3  4]
 [ 9 10  5  6 11 12]]

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
#ML Pipelines
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer 
from sklearn.linear_model import LogisticRegression

df_raw = sns.load_dataset("titanic")
df = df_raw.copy()
#df.isnull().sum()
# Fix missing values
df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
#df.isnull().sum()
#encoding
data = pd.get_dummies(df, columns = ['sex', 'embarked'], drop_first = True)
#data.head()
#Drop columns
columns_keep = ['survived', 'age', 'fare', 'sex_male', 'embarked_Q', 'embarked_S']
data = data[columns_keep]
#data.head()
#Split
X = data.drop('survived', axis=1)
Y = data['survived']
#Train/ Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

#Normalise (Scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

LogisticRegression().fit(X_train_scaled, Y_train)

LogisticRegression()

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [45]:
import numpy as np
import seaborn as sns
df_raw = sns.load_dataset("iris")
df = df_raw.copy()
corr_matrix = df.drop(columns=['species']).corr()
print("Correlation Matrix: ")
print(corr_matrix)

Correlation Matrix:
              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [49]:
# Correlation greater than 90%
to_drop = []
#print(corr_matrix.columns)
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > 0.90:
            colname = corr_matrix.columns[i]
            to_drop.append(colname)
print(set(to_drop))
df_final = df.drop(columns=to_drop)
print(df_final.columns.tolist())

{'petal_width'}
['sepal_length', 'sepal_width', 'petal_length', 'species']

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [53]:
import seaborn as sns
from pandas import isna
df_raw = sns.load_dataset("titanic")
df = df_raw.copy()
def cateogrise_age(age):
    if pd.isna(age):
        return "Unknown"
    elif age < 18:
        return "Child"
    elif age < 60:
        return "Adult"
    else:
        return "Senior"

df['age_group'] = df['age'].apply(cateogrise_age)
survival_rates = df.groupby('age_group')['survived'].mean().sort_values(ascending=False).round(2)

print("Survival Rate by Age Group:")
print(survival_rates)

Survival Rate by Age Group:
age_group
Child      0.54
Adult      0.39
Unknown    0.29
Senior     0.27
Name: survived, dtype: float64

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [66]:
import numpy as np
error = np.random.normal(0, 5, 1000)
print("Mean:", np.mean(error).round(2))
print("Standard deviation: ", np.std(error).round())
limit = 2 * np.std(error)
outliers = error[np.abs(error - (np.mean(error))) > limit]
print(f"Number of 'Extreme' Errors: {len(outliers)}")

Mean: -0.26
Standard deviation:  5.0
Number of 'Extreme' Errors: 39

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [75]:
import pandas as pd
import seaborn as sns
df_raw = sns.load_dataset("tips")
df = df_raw.copy()
df['tip_percentage'] = (df['tip'] / df['total_bill'] * 100).round(2)
#df.head()
summary = df.groupby(['day', 'time'], observed=True).mean(numeric_only=True).round(2)
print(summary)

             total_bill   tip  size  tip_percentage
day  time
Thur Lunch        17.66  2.77  2.46           16.13
     Dinner       18.78  3.00  2.00           15.97
Fri  Lunch        12.85  2.38  2.00           18.88
     Dinner       19.66  2.94  2.17           15.89
Sat  Dinner       20.44  2.99  2.52           15.31
Sun  Dinner       21.41  3.26  2.84           16.69